
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='ecas',
    version='0.1.0',
    description='A CLI to directly read your PR status',
    python_requires='==3.*,>=3.8.0',
    project_urls={"repository": "https://github.com/pievalentin/ecas"},
    author='Pierre Valentin',
    author_email='pievalentin@gmail.com',
    license='MIT',
    entry_points={"console_scripts": ["ecas = ecas.ecas:list_ecas_steps"]},
    packages=['ecas'],
    package_dir={"": "."},
    package_data={},
    install_requires=['beautifulsoup4==4.*,>=4.9.3', 'click==8.*,>=8.0.1',
                      'flask==2.*,>=2.0.1', 'requests==2.*,>=2.25.1'],
    extras_require={"dev": ["autopep8==1.*,>=1.5.7",
                            "dephell==0.*,>=0.8.3", "isort==5.*,>=5.9.1", "pdbpp==0.*,>=0.10.2"]},
)
